CREATE TABLE SMTHNIK ( nam varchar(50), grup number(3));
INSERT INTO SMTHNIK VALUES ('NIKITA', 6);
INSERT INTO SMTHNIK VALUES ('DASHA', 6);
SELECT * FROM SMTHNIK;
DROP TABLE SMTHNIK;

CREATE VIEW view_del AS SELECT nam FROM SMTHNIK WHERE nam = 'NIKITA';
DELETE view_del;
  